//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string FirsName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<System.DateTime> BirtofDate { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> BloodGroupId { get; set; }
        public Nullable<int> EyeColorId { get; set; }
        public Nullable<int> MartialStatusId { get; set; }
        public Nullable<int> MilitaryStatusId { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public Nullable<byte> height { get; set; }
        public string LivingPlace { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Code { get; set; }
        public string Number { get; set; }
        public string IssuingAuthory { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual EyeColor EyeColor { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MartialStatu MartialStatu { get; set; }
        public virtual NAtionality NAtionality { get; set; }
        public virtual MilitaryStatu MilitaryStatu { get; set; }
    }
}
